### PR TITLE
(SERVER-2740) Implement the 'prune' action for Puppetserver's CA CLI

### PR DESCRIPTION
**Pull request by Tu2607**

### CODE REVIEW

**Comment by mwaggett** [comment]
something looks a little funky to me.. why are there two "Implement action 'prune'" commits, but no merge commit?

**Comment by Magisus** [comment]
In general, you shouldn't edit the pre-generated merge commit title. We prefer to leave it as git writes it, so we can clearly see what's a merge.

**Comment by Tu2607** [comment]
> something looks a little funky to me.. why are there two "Implement action 'prune'" commits, but no merge commit?

I might have goofed. Fixed the merge conflict with the version and did `git commit -m "(SERVER-2740)..."`. Of course this is after doing `git merge --log --no-ff 1.x`

**Comment by mwaggett** [comment]
ahh, you should be able to just to `git commit` after resolving conflicts and that will populate the message with the default merge commit message.

**Comment by Tu2607** [comment]
Sorry, habit of tagging thing lately. I'll amend that.

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
