### PR TITLE
Merge 1.x -> main

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Review by mwaggett — APPROVED** [review]

**Comment by Magisus** [comment]
Hm, I don't get those failures locally...

**Comment by Magisus** [comment]
`Facter.value[:hostname]` turning up `nil` seems bad... and doesn't happen for me. Linux thing?

**Comment by mwaggett** [comment]
This didn't happen on your other PR though, did it? Something racy? Rekick?

**Comment by Magisus** [comment]
I'll try it, though I'm wondering about a Facter change... Not sure what version was pulled in last time this ran.

**Comment by Magisus** [comment]
This is the facter fix https://github.com/puppetlabs/facter/pull/2327 but I don't think we need to block on it. However, I would like to get https://github.com/puppetlabs/facter/pull/2327 into this.

**Comment by mwaggett** [comment]
I imagine we'll want to include the facter bump in the 1.x branch and include that in the mergeup?

**Comment by Magisus** [comment]
We don't actually have to bump facter, it's a floating dep.

**Comment by mwaggett** [comment]
ah right. I was misled by "I would like to get puppetlabs/facter#2327 into this." ohhh did you mean to link your other PR?

**Comment by Magisus** [comment]
Updated with the contents of that other PR (which I meant to link)

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
